modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="aemoe" #mandatory

version="1.0" #mandatory

credits="Aden Walker (Coding), Conor Kelly (idk what he did but he's here" #optional

authors="Aden Walker" #optional

description='''This is my epic mod with katanas and epic machinery used to make katanas
'''

[[dependencies.aemoe]] #optional

   modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[36,)" #mandatory

     ordering="NONE"

   side="BOTH"
# Here's another dependency
[[dependencies.aemoe]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
